;;; init.el --- Bootstrap configuration -*- lexical-binding: t; coding: utf-8 -*-
;;; Commentary:
;;
;; Modular Emacs configuration following purcell/emacs.d pattern.
;; Each feature is organized into its own init-*.el file in lisp/
;;
;;; Code:

;; Add lisp directory to load-path
(add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))

;; Declare function for mgrbyte
(declare-function
 #'mgrbyte-delete-trailing-blank-lines
 "~/.emacs.d/lisp/mgrbyte.el")

;; Package management first
(require 'init-elpa)
(require 'init-exec-path)

;; Core settings
(require 'init-defaults)
(require 'init-icons)

;; Completion/Navigation
(require 'init-helm)
(require 'init-projectile)
(require 'init-treemacs)
(require 'init-dashboard)

;; Major modes
(require 'init-org)
(require 'init-python)
(require 'init-clojure)
(require 'init-modes)

;; Tools
(require 'init-git)
(require 'init-dired)
(require 'init-editing)
(require 'init-spell)
(require 'init-misc)

;; Platform/GUI
(require 'init-osx)
(require 'init-gui-frames)

;; Custom functions
(require 'mgrbyte)

;; Custom keybindings
(use-package mgrbyte
  :load-path "lisp"
  :after (git-commit magit)
  :demand t
  :bind (("C-x t w" . delete-trailing-whitespace)
         ("C-c f g" . find-grep-dired))
  :hook ((git-commit-setup . mgrbyte-setup-commit-spelling)
	 (python-mode . mgrbyte-setup-pylsp-for-project)))

;; Code generated by using the Emacs *customize* interfaces goes to its own file.
(require 'f)
(setq custom-file (f-expand "~/.emacs-customize.el"))
(if (f-exists? custom-file)
    (load custom-file))

;; Machine-local config (if exists)
(require 'init-local nil t)

(provide 'init)
;;; init.el ends here
